version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: github.com/hyperyuri/webapi-db
    container_name: api-microsservico-1
    restart: unless-stopped
    tty: true
    ports:
      - "25433:5432"
    environment:
      POSTGRES_DB: vacancies
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/webapi-mvc
    volumes:
      - webapi-mvc:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  webapi-mvc:
