global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: myapp
  static_configs:
  - targets: ["192.168.1.72:5000"]
  metrics_path: '/metrics' # Define o caminho do endpoint das métricas
  scheme: 'http' # Especifica o esquema utilizado (http ou https)